#!/bin/csh -f

# Set Variables
set source = "odbToMat"
set abaqusIncludeDir = "./abaqusInclude/linux"
set abaqusLibDir = "./abaqusLib/linux"
set matIncludeDir = "./matInclude/linux"
set matLibDir = "./matLib/linux"
set odbToMatIncludeDir = "./odbToMatInclude"
set odbToMatLibDir = "./odbToMatLib"

echo Resetting Library Search Path...

setenv LD_LIBRARY_PATH ${abaqusLibDir}:${matLibDir}:${odbToMatLibDir}


./$source.exe $*
